### ISSUE TITLE
HDR does not work for Microsoft Windows operating systems

### ISSUE THREAD

**Issue by gotwig** [lsalzman/tesseract#12]
When I enable HDR, I see the following image.

After disabling it, all works normal.

![sauerbraten](https://f.cloud.github.com/assets/1532942/21877/1f4feaf4-49d9-11e2-8a47-52462294e111.png)

**Comment by lsalzman** [comment]
Insufficient information coupled with an overly general conclusion as to the problem.

Tesseract has been extensively tested and used on Windows and there is no problem that has been reported like this ever.

So, it would be fair to say it is unique to your GPU hardware/driver configuration. Please report this information.

**Comment by gotwig** [comment]
I've tested with  ATI Radeon HD 4300/4500 Series

**Comment by gotwig** [comment]
I've tested with  ATI Radeon HD 4300/4500 Series

**Comment by gotwig** [comment]
I've tested with  ATI Radeon HD 4300/4500 Series

**Comment by lsalzman** [comment]
I have another confirmation of a similar problem with the HD 4530, but does not occur with 4800 series or above, or on 3000 serie. But until I have access to someone with this specific hardware who is willing to work with me over IRC to fix this, I can't do much about it right now.

**Comment by lsalzman** [comment]
Testing confirmed the problem was due to ATI not supporting blending when rendering to packed-float (R11G11B10F) format on GPUs labeled variously within Mobility Radeon HD 4x00-5x00 range. I have simply blacklisted this format on cards in that range and instead use the RGB10 formats. This should prevent users from running into the issue.
