### ISSUE TITLE
[Question] Do you have a tesseract sauerbraten available for download that can build properly??

### ISSUE THREAD

**Issue by 2-bithacker** [lsalzman/tesseract#33]
Do you?  If there was one, it would be amazing!  I have been a big sauer fan for a while and if you had sauerbraten powered by tesseract like the video, it would be the ultimate videogame.

**Comment by Calinou** [comment]
I've gotten this repository's latest commit as of writing (https://github.com/lsalzman/tesseract/commit/7dc2087a87b54e16e9fa52b7d2f33952c1e86c34) to compile on Fedora 34 with GCC. The only change I had to make to the source code is here, as the SDL Mixer API has changed since: https://github.com/lsalzman/tesseract/blob/7dc2087a87b54e16e9fa52b7d2f33952c1e86c34/src/engine/sound.cpp#L194

Replace line 194 with:

```cpp
if(musicrw) music = Mix_LoadMUS_RW(musicrw, NULL);
```

You will need the `packages/` folder from a Sauerbraten Collect Edition installation (**not** the latest 2020 edition!). You can extract it from the [Linux download](https://sourceforge.net/projects/sauerbraten/files/sauerbraten/2013_01_04/sauerbraten_2013_04_04_collect_edition_linux.tar.bz2/download) using 7-Zip or similar.

Tesseract should build and run successfully with the above change, but you'll notice a few things:

- [x] https://github.com/Calinou/tesseract/commit/da8f791cf1cf751f048bce6d14e7c572c437c1ba, https://github.com/Calinou/tesseract/commit/883f2597d3ff4c91f2efd7016d7d56db3cbf503b, https://github.com/Calinou/tesseract/commit/c979044aa33e064a4298cbf1333ff8f74714c9fa Maps with an old format such as `metl2`, `metl3` and `metl4` cannot be loaded.
- [ ] Mapmodels can't be loaded in some maps such as `ot` due to mismatching mapmodel IDs. Sometimes, the wrong mapmodels will be loaded too. Also, colliding with some mapmodels will cause your character to become stuck and eventually fly into the void (due to how I sloppily reverted https://github.com/Calinou/tesseract/commit/2907ed075c62323555248dce654464df209ed30e).
- Some maps such as `DM_BS1` run very slowly despite their small size, due to the high number of lights. Maps with fewer lights such as `ot` run very well in comparison.
  - [ ] I suppose this could be improved by detecting maps with too many lights on load. If a map has too many lights:
    - Skip lights smaller than a certain radius.
    - Make the other lights' radius slightly larger (and/or brighter) to compensate.
- [ ] Some maps such as `abbey` or `arabic` use a large point light instead of a sun, which reduces shadow rendering quality and prevents GI from working (as it only works for directional lighting in Tesseract). A proper `/sunlight` should be used instead, and the sun entity should be removed.
  - Find a sun light (if any) in the map at load time. Typically, this is either a light with radius `0` or the largest radius of all lights.
  - Guess a sunlight direction based on the light entity's position and ignore this light.
- [ ] Some maps look too dark, even when using a proper sunlight with global illumination. Per-map ambient light overrides are likely the best way to fix this, but we can't distribute modified `.cfg` files of the original maps so a custom system will have to be designed for this. Examples:
  - `ot` roughly matches the original appearance with `/ambient 60 55 50` and `/giscale 1.0`.
  - `l_ctf` roughly matches the original appearance with `/ambient 45 45 45`.
- [x] https://github.com/Calinou/tesseract/commit/34d5e2f6725d83a2c150b95c8d3fa45743a83cf4 Maps won't have working smooth shading on curved surfaces until you run `/calclight` (which is a very fast operation). An automatic workaround would be to run `/calclight` every time a map is loaded.
- Some backwards-incompatible changes were designed for Tesseract's standalone release, but these do not work with Sauerbraten assets:
  - [x] https://github.com/Calinou/tesseract/commit/76266e0476c7d998d138375a740a4fa2cd2c9ab9 Texture scale is wrong (it's half what it should be for Sauerbraten maps).
  - [x] https://github.com/Calinou/tesseract/commit/2907ed075c62323555248dce654464df209ed30e, https://github.com/Calinou/tesseract/commit/9133efccd3f05cddf5ceb3adb3e7bd655b6477ac, https://github.com/Calinou/tesseract/commit/d3b66e124d8f0da6f8a38abd694a134216046b93 Models are rotated the wrong way, which means the hudgun is not visible most of the time.
  - [x] https://github.com/Calinou/tesseract/commit/0e2a5703316b84f9c33d443c5db893c94fbc227b, https://github.com/Calinou/tesseract/commit/6a6ec911f6b40cb201468f98dc6ae0c6abbba554 The forward and airborne movement speed bonuses were removed.
  - [ ] Multiplayer protocol is not compatible with Sauerbraten Collect Edition servers (likely due to the gameplay change listed above).
- [x] https://github.com/Calinou/tesseract/commit/33ae2a14b51b12507ea32bd3b67cb2e8c6b9db4c Some map CFG files try to use unknown commands, causing error spam in the console when loading specific maps. So far, I've noticed this with the `md5glare`, `mdlalphadepth` and `texffenv` commands.

I have a fork with some fixes included: https://github.com/Calinou/tesseract

I'll see if I can further improve compatibility with Sauerbraten Collect Edition, and eventually provide precompiled builds using GitHub Actions or similar.

**Comment by 2-bithacker** [comment]
Thanks gigatons!

**Comment by 2-bithacker** [comment]
Do you happen to know how to fix this
![2022-02-15_16 58 44_ot_ffa](https://user-images.githubusercontent.com/90713990/154164257-f02c2084-2246-4eef-9e8e-17c3b34210fd.png)
![2022-02-15_16 59 39_ot_ffa](https://user-images.githubusercontent.com/90713990/154164264-d47aaff6-52fc-402e-b614-7d91bba7c034.png)
?

**Comment by 2-bithacker** [comment]
See?  The guy is sideways.  What is wrong?

**Comment by Calinou** [comment]
> See? The guy is sideways. What is wrong?

I just fixed the texture scale and model rotation to match the expected Sauerbraten values in my fork. Try running `git pull` and compile it again.

PS: In the future, please use the **Edit** button (located behind the **…** icon in the top-right corner of your comments) instead of multi-posting.

**Comment by 2-bithacker** [comment]
I apoligize for that.  *embarrassed* in what directory do I run `git pull`?  Do I just do it in the cd or in the tesseract folder?  Also, the fork does not compile at all.

**Comment by Calinou** [comment]
> I am embarassed to ask this, but in what directory do I run git pull? Do I just do it in the cd or in the tesseract folder?
The fork does not seem to compile at all.

You can run `git pull` anywhere in the cloned fork repository, then compile it by running `make && make install` in the `src` folder. (You can also use `make -C src install` from the root Tesseract directory if you don't want to `cd src` first.)

**Comment by 2-bithacker** [comment]
Thank you,  but it said it was up to date, and the guy is still sideways.  like the bullet goes the right direction, but te model itself is messed up.   Is it somewhere in the playermodel data?

**Comment by Calinou** [comment]
> Thank you, but it said it was up to date, and the guy is still sideways.

Did you compile Tesseract from source again? The change is in the C++ source, not in the model files.

**Comment by 2-bithacker** [comment]
yeah.  Could you point out to me the names of the changed files?  I tried building the fork and it didn't work at all.  Here are the errors. 
`optiplex780@super-OptiPlex-780:~/Downloads/tesseract-master(2)/tesseract-master/src$ make install
cd enet; ./configure --enable-shared=no --enable-static=yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
./configure: eval: line 2430: syntax error near unexpected token `('
./configure: eval: line 2430: `${SHELL} /home/optiplex780/Downloads/tesseract-master(2)/tesseract-master/src/enet/missing --run true'
make: *** [Makefile:150: enet/Makefile] Error 2
optiplex780@super-OptiPlex-780:~/Downloads/tesseract-master(2)/tesseract-master/src$ `

**Comment by Calinou** [comment]
@2-bithacker Does it work if you run `git revert --no-edit 1bdcb6c8722aaa8a6865006216fec90c1963c735` then compile again?

(By the way, which Linux distribution are you using? `src/enet/configure` was automatically modified by my Fedora 34 setup when compiling, so I committed it.)

**Comment by 2-bithacker** [comment]
the `git revert --no-edit 1bdcb6c8722aaa8a6865006216fec90c1963c735` gives the error `fatal: not a git repository (or any of the parent directories): .git`
I am running ubuntu 22.04.

**Comment by Calinou** [comment]
> the git revert --no-edit 1bdcb6c8722aaa8a6865006216fec90c1963c735 gives the error fatal: not a git repository (or any of the parent directories): .git

You need to run that command within the cloned Tesseract repository (my fork, specifically).

**Comment by 2-bithacker** [comment]
It said

`error: your local changes would be overwritten by revert.
hint: commit your changes or stash them to proceed.
fatal: revert failed`

Not my repo, so I can't commit the changes.

**Comment by Calinou** [comment]
> It said
>
> `error: your local changes would be overwritten by revert. hint: commit your changes or stash them to proceed. fatal: revert failed`

Run `git reset --hard` before running the `git revert` command I mentioned. If that doesn't suffice, run `git clean -dfx`, but beware as this will remove all untracked files within the Tesseract repository (including your compiled binary and `packages/` folder).

> Not my repo, so I can't commit the changes.

You *can* commit changes to a Git repository without having write access to the repository in question. However, you can't *push* those changes.

**Comment by 2-bithacker** [comment]
That did it!!  THANKS!!  The RD Sauerclan will be VERY pleased!  (don't worry, no cheating will happen) Thanks!!!
